# Generated by Django 4.0.6 on 2022-07-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_player_playerstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='uid',
            field=models.IntegerField(),
        ),
    ]
