# Generated by Django 4.0.6 on 2022-07-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_player_uid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerStats',
        ),
        migrations.AlterField(
            model_name='player',
            name='uid',
            field=models.IntegerField(default=0),
        ),
    ]
