# Generated by Django 4.0.6 on 2022-07-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_delete_playerstats_alter_player_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='character_main',
            field=models.CharField(default='Heizou', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='characters_obtained',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='days_played',
            field=models.IntegerField(default=0),
        ),
    ]
