# Generated by Django 4.0.6 on 2022-07-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_player_character_main_player_characters_obtained_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='character_main',
            field=models.CharField(default='', max_length=50),
        ),
    ]
